version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  
  app:
    build: .
    container_name: task-manager-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/task-manager-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
