version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  
  app:
    build: .
    container_name: task-manager-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq  
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-manager-api
      - RABBITMQ_URI=amqp://rabbitmq:5672 
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - app-network

  worker:
    build: .
    container_name: task-manager-api-worker
    command: node worker.js 
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://mongo:27017/task-manager-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge